version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:12.11
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE_NAME}
    ports:
      - ${POSTGRES_EXPOSED_PORT}:5432
    volumes:
      - ./databases/postgresql/${POSTGRES_DATABASE_NAME}:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    container_name: redis
    image: redis:7.0.4
    restart: unless-stopped
    ports:
      - ${REDIS_EXPOSED_PORT}:6397
  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    environment:
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DATABASE_NAME}
      - FLYWAY_SCHEMAS=${MIGRATION_SCHEMA}
      - FLYWAY_LOCATIONS=filesystem:/flyway/sql/
      - FLYWAY_CONNECT_RETRIES=60
      - FLYWAY_SQL_MIGRATION_PREFIX=V
      - FLYWAY_SQL_MIGRATION_SEPARATOR=__
      - FLYWAY_VALIDATE_MIGRATION_NAMING=true
    command: migrate
    volumes:
      - ${MIGRATION_SRC}:/flyway/sql
    depends_on:
      - postgres